export const mockData = {
  postcode: "1234AB",
  huisnummer: "99",
  stroom_per_jaar_kWh: 1250,
  gas_per_jaar_m3: 1100,
  deals: [
    {
      cashback: 290,
      tarief: "vast",
      looptijd: "1 jaar",
      stroom: "groene stroom",
      gas: null,
      klantbeoordeling: 8.1,
      kosten_per_maand_euro: 157.84,
      kosten_per_jaar_euro: 1894.13,
    },
    {
      cashback: 440,
      tarief: "vast",
      looptijd: "1 jaar",
      stroom: "NL groene stroom",
      gas: null,
      klantbeoordeling: 7.9,
      kosten_per_maand_euro: 154.9,
      kosten_per_jaar_euro: 1858.76,
    },
    {
      cashback: 400,
      tarief: "vast",
      looptijd: "1 jaar",
      stroom: "groene stroom",
      gas: null,
      klantbeoordeling: 7.6,
      kosten_per_maand_euro: 155.72,
      kosten_per_jaar_euro: 1868.64,
    },
    {
      cashback: 400,
      tarief: "vast",
      looptijd: "1 jaar",
      stroom: "NL groene stroom",
      gas: null,
      klantbeoordeling: 7.6,
      kosten_per_maand_euro: 156.22,
      kosten_per_jaar_euro: 1874.64,
    },
    {
      cashback: 470,
      tarief: "vast",
      looptijd: "1 jaar",
      stroom: "groene stroom",
      gas: null,
      klantbeoordeling: 6.7,
      kosten_per_maand_euro: 156.5,
      kosten_per_jaar_euro: 1878.03,
    },
    {
      cashback: 400,
      tarief: "vast",
      looptijd: "1 jaar",
      stroom: "NL groene stroom",
      gas: "deels groen gas",
      klantbeoordeling: 8.3,
      kosten_per_maand_euro: 157.06,
      kosten_per_jaar_euro: 1884.76,
    },
    {
      cashback: 340,
      tarief: "vast",
      looptijd: "1 jaar",
      stroom: "NL groene stroom",
      gas: "CO2-gecompenseerd gas",
      klantbeoordeling: 7.6,
      kosten_per_maand_euro: 157.61,
      kosten_per_jaar_euro: 1891.35,
    },
    {
      cashback: 290,
      tarief: "vast",
      looptijd: "1 jaar",
      stroom: "groene stroom",
      gas: null,
      klantbeoordeling: 8.1,
      kosten_per_maand_euro: 157.84,
      kosten_per_jaar_euro: 1894.13,
    },
    {
      cashback: 300,
      tarief: "vast",
      looptijd: "1 jaar",
      stroom: "NL groene stroom",
      gas: "CO2-gecompenseerd gas",
      klantbeoordeling: 8.4,
      kosten_per_maand_euro: 158.28,
      kosten_per_jaar_euro: 1899.4,
    },
    {
      cashback: 370,
      tarief: "vast",
      looptijd: "1 jaar",
      stroom: "groene stroom",
      gas: null,
      klantbeoordeling: 7.8,
      kosten_per_maand_euro: 160.62,
      kosten_per_jaar_euro: 1927.47,
    },
    {
      cashback: 370,
      tarief: "vast",
      looptijd: "1 jaar",
      stroom: "NL groene stroom",
      gas: "CO2-gecompenseerd gas",
      klantbeoordeling: 7.8,
      kosten_per_maand_euro: 160.95,
      kosten_per_jaar_euro: 1931.38,
    },
  ],
}
